### ISSUE TITLE
Build and test lib folder before publishing

### ISSUE THREAD

**Issue by AndersCan** [AndersCan/typed-option#3]
Ensure lib folder is always built and tested before publishing. This to avoid a stale package being published to npm

Scripts: https://docs.npmjs.com/misc/scripts

**Comment by mceachen** [comment]
Have you checked out [np](https://github.com/sindresorhus/np)? 

(Make sure you run it from `npm`, not `yarn`).

**Comment by AndersCan** [comment]
Thanks for the tip. I've come across np before, but I have not tried it yet. Might try implementing it at at later date.

**Comment by AndersCan** [comment]
> Narrator: He did not

**Comment by mceachen** [comment]
FWIW I've found `np` to be buggy between releases.  https://github.com/release-it/release-it is much more solid. Example config here: https://github.com/photostructure/exiftool-vendored.js/blob/f204efa8b6aed7dcfda122e6c84ca1c29f6c16e7/package.json#L45
